spring.application.name=taskmanager

spring.datasource.url=jdbc:postgresql://localhost:5432/team_task_manager
spring.datasource.username=taskmanager
spring.datasource.password=taskmanager

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
